apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-provider
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: git@github.com:extrain-benjamin/apps-of-apps-test.git
    targetRevision: main
    path: log-provider/
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
